server:
  port: 8180
spring:
  ai:
    mcp:
      client:
        enabled: true
        name: mcp-client
        sse:
          connections:
            mcp-server-1:
              url: http://localhost:8080
            mcp-server-2:
              url: http://localhost:8080
    ollama:
      base-url: http://192.168.8.228:11434
      chat:
        options:
          # 需要支持tools的模型
          model: llama3.1
