server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activiti?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  activiti:
    history-level: full
    database-schema-update: true
    check-process-definitions: true
    process-definition-location-prefix: classpath:/processes/
  jpa:
    hibernate:
      ddl-auto: update
      open-in-view: false
