import pandas as pd

x = pd.Series([0.25, 0.5, 0.75, 1.0])
print(x[1:3])
print(x.loc[1:3])
print(x.iloc[1:3])
x = pd.Series([0.25, 0.5, 0.75, 1.0], index = ["a", 'b', 'c', 'd'])
print(x['b':'d'])
print(x.loc['b':'d'])
# print(x.iloc['b':'d'])
print(x)
print(1 in x)
print('a' in x)
print(x.keys())
print(x.index)
print(x.values)
# print(x.items())
print(list(x.items()))
print(x.T)