server:
  port: 8080
spring:
  ai:
    mcp:
      server:
        name: mcp-server
        version: 1.0.0
        type: SYNC
        instructions: "mcp-server"
        sse-message-endpoint: /mcp/messages
        capabilities:
          tool: true
          prompt: true
          resource: true
          completion: true
    ollama:
      base-url: http://192.168.8.228:11434
