头部:
  发色: [ "黑色", "金色", "银色", "灰色", "红色" ]
  发型: [ "短发", "长发", "披肩发", "大波浪" ]
  眉毛: [ "弯眉", "直眉", "浓眉" ]
  眼睛: [ "小眼", "中眼", "大眼", "眯眼" ]
  鼻子: [ "小鼻", "中鼻", "大鼻" ]
  牙齿: [ "露齿", "不露" ]
  嘴巴: [ "小嘴", "中嘴", "大嘴" ]
  口红: [ "深红", "红色", "粉红" ]
  表情: [ "发呆", "休息", "高兴", "自信", "悲伤", "严肃", "冷漠", "生气", "轻蔑", "嘲笑", "感动", "鬼脸", "疑问", "害怕", "惊讶", "讨厌", "害羞", "无奈" ]
  脸型: [ "圆脸", "方脸", "长脸", "鹅蛋", "椭圆", "三角" ]
上身:
  乳房: [ "玲珑", "匀称", "圆润", "丰满", "巨乳" ]
  手型: [ "叉腰", "舒展", "紧握", "插兜" ]
  腰部: [ "纤细", "婀娜" ]
下身:
  臀部: [ "紧实", "翘臀", "丰臀", "肥臀" ]
  腿型: [ "直立", "稍息", "半蹲", "下蹲", "盘腿" ]
衣着:
  色调: [ "黑白", "红色", "蓝绿" ]
  衣服: [ "衬衫", "裙子", "泳衣", "羽绒服" ]
  裤子: [ "休闲裤", "牛仔裤", "马面裙" ]
  鞋子: [ "赤脚", "增高鞋", "高跟鞋", "运动鞋" ]
饰品:
  头饰: [ "蝴蝶结", "贝雷帽" ]
  耳饰: [ "耳环" ]
  眼饰: [ "墨镜" ]
  脸饰: [ "口罩" ]
  首饰: [ "手镯", "手表" ]
  包包: [ "钱包", "挎包", "手提包", "双肩包" ]
特征:
  肤色: [ "黄色", "白色", "褐色", "黑色" ]
  皮肤: [ "圆润", "光滑", "细嫩" ]
  性格: [ "傲娇", "萝莉", "温柔", "淑女", "熟女" ]
  年龄: [ "金钗之年", "豆蔻年华", "及笄之年", "桃李年华", "花信年华", "半老徐娘", "人老珠黄" ]
  身高: [ "娇小", "中等", "高挑" ]
  体型: [ "虚弱", "消瘦", "苗条", "丰满", "健硕", "肥胖" ]
  姿态: [ "端坐", "站立", "斜靠", "侧卧", "游泳", "半蹲", "下蹲" ]
  职业: [ "空姐", "教师", "学生" ]
环境:
  天气: [ "晴朗", "阴天", "小雨", "大雨" ]
  前景: [ "郊外", "客厅", "商业街" ]
  背景: [ "郊外", "客厅", "商业街" ]
