七言绝句:
  rhythmic: 七言绝句
  example : |
    月落乌啼霜满天，江枫渔火对愁眠。
    姑苏城外寒山寺，夜半钟声到客船。
  fontSize: 28
  segmentSize: 4
  segmentRule: [ 7, 7, 7, 7 ]
  participleRule: [
    2, 2, 3, 2, 2, 3,
    2, 2, 3, 2, 2, 3
  ]
虞美人·春花秋月何时了:
  rhythmic: 虞美人
  example : |
    春花秋月何时了，往事知多少？小楼昨夜又东风，故国不堪回首月明中。
    雕栏玉砌应犹在，只是朱颜改。问君能有几多愁？恰似一江春水向东流。
  fontSize: 56
  segmentRule: [ 7, 5, 7, 9, 7, 5, 7, 9 ]
  segmentSize: 8
  participleRule: [
    2, 2, 3, 2, 3, 2, 2, 3, 2, 2, 2, 3,
    2, 2, 3, 2, 3, 2, 2, 3, 2, 2, 2, 3
  ]
蝶恋花·庭院深深深几许:
  rhythmic: 蝶恋花
  example : |
    庭院深深深几许，杨柳堆烟，帘幕无重数。玉勒雕鞍游冶处，楼高不见章台路。
    雨横风狂三月暮，门掩黄昏，无计留春住。泪眼问花花不语，乱红飞过秋千去。
  fontSize: 60
  segmentRule: [ 7, 4, 5, 7, 7, 7, 4, 5, 7, 7 ]
  segmentSize: 10
  participleRule: [
    2, 2, 3, 2, 2, 2, 3, 2, 2, 3, 2, 2, 3,
    2, 2, 3, 2, 2, 2, 3, 2, 2, 3, 2, 2, 3
  ]
