# 公共配置
config:
  tmp: /tmp
# REST监听
rest-server:
  host: 0.0.0.0
  port: 8080
# 音频配置
audio:
  path: /data/lifuren/audio
  model: 
  client: audio-shikuang
  clients:
    - audio-shikuang
# 图片配置
video:
  path: /data/lifuren/video
  model: 
  client: video-wudaozi
  clients:
    - video-wudaozi
  length: 24
# 诗词配置
poetry:
  path: /data/lifuren/poetry
  model: 
  client: poetry-lidu
  clients:
    - poetry-lidu
    - poetry-suxin
  dims: 768
  length: 4
  rag-size: 4
  # char|rhythm
  embedding-participle: rhythm
# ElasticSearch配置
elasticsearch:
  api: http://localhost:9200
  username: elastic
  password: elastic
  # NONE|Basic|Token
  auth-type: Basic
# Ollama配置
# https://github.com/ollama/ollama/blob/main/docs/api.md
ollama:
  api: http://localhost:11434
  username: 
  password: 
  # NONE|Basic|Token
  auth-type: NONE
  dims: 768
  path: /api/embed
  model: quentinz/bge-base-zh-v1.5
  # model: quentinz/bge-large-zh-v1.5
  # model: quentinz/bge-small-zh-v1.5
  options: {}
# pepper配置
pepper:
  dims: 768
  